version: '3.3'
services:
  gmapdb:
    image: postgres
    container_name: gmapdb
    restart: always
    #network_mode: bridge  network_mode and networks cannot be combined
    networks:
      - mynet
    expose:
      - "5432"
    environment:
      POSTGRES_DB: gmap
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: gmapdb
    # Where our data will be persisted
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"


  userservice-app:
    restart: on-failure
    container_name: userservice
    networks:
      - mynet
    build:
      context: userservice
      dockerfile: Dockerfile
    expose:
      - "8080"
    ports:
      - 8080:8080
    environment:
      POSTGRES_HOST: gmapdb:5432
      SPRING_DATASOURCE_URL: jdbc:postgresql://gmapdb:5432/gmap
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - gmapdb


  bidservice-app:
    restart: on-failure
    container_name: bidservice
    networks:
      - mynet
    build:
      context: bidservice
      dockerfile: Dockerfile
    expose:
      - "8081"
    ports:
      - 8081:8081
    environment:
      POSTGRES_HOST: gmapdb:5432
      SPRING_DATASOURCE_URL: jdbc:postgresql://gmapdb:5432/gmap
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - gmapdb
      - "userservice-app"
# Names our volume
volumes:
  db_data:
networks:
  mynet: