gmap:
  bidservice:
    url: http://localhost:8081/bidservice

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
server:
  port: 8080
  servlet:
    context-path: /userservice

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 1
        minimumNumberOfCalls: 1
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 20s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
          - java.io.IOException
          - org.springframework.web.client.ResourceAccessException
    instances:
      userservice:
        baseConfig: default
  retry:
    configs:
      default:
        maxRetryAttempts: 3
        waitDuration: 10s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
          - org.springframework.web.client.ResourceAccessException
        ignoreExceptions:
          - java.util.concurrent.TimeoutException
    instances:
      userservice:
        baseConfig: default

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true
---
spring:
  profiles: h2
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:localdb
    username: sa
  flyway:
    baselineOnMigrate: true
    enabled: true
    locations: classpath:db/migration/h2
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: PUBLIC
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          batch_size: 10
          lob:
            non_contextual_creation: true
        order_inserts: true
    show-sql: true
---
spring:
  profiles: postgres
  datasource:
    driverClassName: org.postgresql.Driver
    password: postgres
    url: jdbc:postgresql://localhost:5432/gmap
    username: postgres
  flyway:
    baselineOnMigrate: true
    enabled: true
    schemas: public
    locations: classpath:db/migration/postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: PUBLIC
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 10
          lob:
            non_contextual_creation: true
        order_inserts: true
    show-sql: true
# overriding only for postgres profile which is assumed to be run only in container, profile h2 is for local development
gmap:
  bidservice:
    url: http://bidservice:8081/bidservice